Add kill, restart, start, stop commands.

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -38,10 +38,26 @@ version_for() {
   dpkg-deb -I $deb | grep Version | awk '{print $2}'
 }
 
-extract_version() {
+extract_version_from_deb() {
   local main_deb=$(ls *.deb | egrep "^${package}_.*")
-  test -z "$main_deb" && { echo "Unable to locate deb archive: ${package}_<version>.deb" >&2; exit 1; }
+  if [ -z "$main_deb" ]; then
+    echo "A 'version' parameter was not supplied, and a deb archive '${package}_<version>.deb', from which a version can be extracted, could not be found." >&2
+    exit 1
+  fi
   version_for $main_deb
+}
+
+resolve_version() {
+  local version_dir=$(jq -r '.params.version // ""' < $payload)
+  if [ -n "$version_dir" ]; then
+    local version_file="${source}/${version_dir}/number"
+    local version=$(cat $version_file)
+    test -z "$version" && { echo "version not found in $version_file"; exit 1; }
+  else
+    local version=$(extract_version_from_deb)
+  fi
+
+  echo $version
 }
 
 repository=$(attr source repository)
@@ -57,7 +73,7 @@ architecture=$(jq -r '.source.architecture // "amd64"' < $payload)
 
 cd $source/$debs
 
-version=$(extract_version)
+version=$(resolve_version)
 
 for f in $(ls *.deb); do
   put $f
